--- include/linux/Kbuild
+++ include/linux/Kbuild
@@ -227,7 +227,6 @@
 header-y += kdev_t.h
 header-y += kernel.h
 header-y += kernelcapi.h
-header-y += kernel-page-flags.h
 header-y += keyboard.h
 header-y += keyctl.h
 header-y += l2tp.h
